<?php
/* Saltanat News Karachi — weekly issue uploader. Read ADMIN_PASS from /home/noorgeec/cred/slt.env, outside public web root. */
declare(strict_types=1);
session_start();
$configPath = dirname(__DIR__) . '/cred/slt.env';
$adminPassword = '';
if (is_readable($configPath)) {
  foreach ((array) file($configPath, FILE_IGNORE_NEW_LINES) as $line) {
    $line = trim((string) $line);
    if ($line === '' || str_starts_with($line, '#') || !str_contains($line, '=')) { continue; }
    [$key, $value] = explode('=', $line, 2);
    if (trim($key) === 'ADMIN_PASS') { $adminPassword = trim($value, " \t\n\r\0\x0B\"'"); break; }
  }
}
if ($adminPassword === '') { http_response_code(503); exit('Admin setup is incomplete. Add ADMIN_PASS to /home/noorgeec/cred/slt.env outside the public web directory.'); }
if (isset($_POST['logout'])) { session_unset(); session_destroy(); header('Location: admin.php'); exit; }
if (isset($_POST['password']) && hash_equals($adminPassword, (string)$_POST['password'])) { session_regenerate_id(true); $_SESSION['saltanat_admin'] = true; header('Location: admin.php'); exit; }
$loggedIn = !empty($_SESSION['saltanat_admin']); $message = '';
if ($loggedIn && isset($_POST['upload_issue'])) { $label = trim((string)($_POST['label'] ?? '')); $date = trim((string)($_POST['date'] ?? '')); $issueId = trim((string)($_POST['issue_id'] ?? '')); $upload = $_FILES['pdf'] ?? null; if (!$upload || $upload['error'] !== UPLOAD_ERR_OK || strtolower(pathinfo($upload['name'], PATHINFO_EXTENSION)) !== 'pdf') { $message = 'براہ کرم درست PDF فائل منتخب کریں۔'; } elseif ($label === '' || $date === '' || $issueId === '') { $message = 'شمارہ نمبر، عنوان اور تاریخ لازمی ہیں۔'; } else { $safeName = 'Saltanat-' . preg_replace('/[^A-Za-z0-9_-]/', '', $issueId) . '-' . date('dMY', strtotime($date)) . '.pdf'; $media = __DIR__ . '/media'; if (!is_dir($media)) { mkdir($media, 0755, true); } if (move_uploaded_file($upload['tmp_name'], $media . '/' . $safeName)) { $archivePath = $media . '/issues.json'; $archive = is_file($archivePath) ? json_decode((string)file_get_contents($archivePath), true) : ['issues' => []]; $archive = is_array($archive) ? $archive : ['issues' => []]; array_unshift($archive['issues'], ['id' => $issueId, 'label' => $label, 'date' => $date, 'file' => $safeName]); file_put_contents($archivePath, json_encode($archive, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT), LOCK_EX); $message = 'نیا شمارہ اپ لوڈ ہو گیا اور آرکائیو میں شامل کر دیا گیا ہے۔'; } else { $message = 'فائل محفوظ نہیں ہو سکی۔ media/ فولڈر کی permission چیک کریں۔'; } } }
?><!doctype html><html lang="ur" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Saltanat Admin</title><style>body{margin:0;background:#f7f0e2;color:#16213e;font-family:Tahoma,serif}.box{width:min(550px,calc(100% - 32px));margin:8vh auto;background:#fffaf0;border:1px solid #d9c9ae;padding:28px;box-shadow:0 12px 35px #3b2c1815}h1{margin-top:0}label{display:block;margin:14px 0 5px;font-weight:bold}input{width:100%;box-sizing:border-box;padding:11px;border:1px solid #cdbb9d}button,a.button{display:inline-block;margin-top:18px;border:0;background:#16213e;color:#fff;padding:11px 17px;text-decoration:none;cursor:pointer}.note{background:#f2e7d4;padding:10px;color:#4a5870}.success{color:#17656a;font-weight:bold}</style></head><body><main class="box"><?php if(!$loggedIn): ?><h1>سلطنت نیوز — Admin</h1><p class="note">صرف مجاز ایڈیٹر کے لیے۔ لاگ اِن پاس ورڈ `/home/noorgeec/cred/slt.env` میں public web directory سے باہر رکھا گیا ہے۔</p><form method="post"><label>پاس ورڈ</label><input type="password" name="password" required autofocus><button type="submit">لاگ اِن</button></form><?php else: ?><h1>نیا ہفتہ وار شمارہ</h1><p>ایک PDF اپ لوڈ کریں۔ سسٹم اس کو `media/` میں محفوظ کر کے آرکائیو فائل خود اپ ڈیٹ کرے گا۔</p><?php if($message): ?><p class="success"><?= htmlspecialchars($message, ENT_QUOTES, 'UTF-8') ?></p><?php endif; ?><form method="post" enctype="multipart/form-data"><label>شمارہ نمبر</label><input name="issue_id" placeholder="مثلاً 11" required><label>عنوان</label><input name="label" placeholder="مثلاً شمارہ 11" required><label>اشاعت کی تاریخ</label><input type="date" name="date" required><label>PDF فائل</label><input type="file" name="pdf" accept="application/pdf" required><button name="upload_issue" value="1">PDF اپ لوڈ اور شائع کریں</button></form><form method="post"><button name="logout" value="1">لاگ آؤٹ</button></form><p><a class="button" href="index.html">ویب سائٹ دیکھیں</a></p><?php endif; ?></main></body></html>
